config/routes.rb
Rails.application.routes.draw do
  mount Tolk::Engine => '/y', :as => 'tolk'
  devise_for :admin_users, ActiveAdmin::Devise.config
  # scope ':locale', defaults: { locale: I18n.locale } do
  #   ActiveAdmin.routes(self)
  # end
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :clients
  root "book#index"


  resources :clients, :controller => :book
  resources :reservations, only: [ :index, :create, :update ], :controller => :book
  resources :rooms
  get 'standart', to: :standart, controller: 'rooms'
  get 'luxe', to: :standart, controller: 'rooms'

  resources :about_us
  resources :gallery
  resources :prices
  resources :contact
end

app/models/room.rb
class Room < ApplicationRecord
  validates :number, uniqueness: true

  enum type_of_room: [ :standart, :luxe ]

  has_many :reservations
  has_many :room_dates

  def to_s
    type_of_room
  end

  def type_of_room_ru
    if type_of_room == "standart"
      "Стандарт"
    elsif type_of_room == "luxe"
      "Люкс"
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @room_standart = Room.find_by(type_of_room: "standart")
    @room_luxe = Room.find_by(type_of_room: "luxe")
  end

  def standart
    @reservation = Reservation.new
    @client = Client.new
    @room = Room.find_by(type_of_room: "standart")
  end

  def luxe
    @reservation = Reservation.new
    @client = Client.new
    @room = Room.find_by(type_of_room: "luxe")
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<!-- subheader -->
<section id="subheader">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>
          КОМНАТЫ
        </h1>
      </div>

      <!-- devider -->
      <div class="col-md-12">
        <div class="devider-page">
          <div class="devider-img-right">
          </div>
        </div>
      </div>

      <div class="col-md-12">
        <ul class="subdetail">
          <li>
            <a href="/">ДОМОЙ</a>
          </li>

          <li class="sep">/
          </li>

          <li>
            <a href="/prices">УТОЧНИТЬ ЦЕНЫ</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- subheader end -->

<!-- room -->
<section class="whitepage" aria-label="rooms">
<div class="container">
 <div class="row">

 <div class="col-md-6">
  <div class="room">
   <%= image_tag("rooms/img1.jpg", :alt => "room img", :class => "img-responsive", ) %>
   <div class="heading">Стандарт</div>
   <div class="devider-rooms"></div>
   <div class="price">₴<%= @room_standart.room_dates.where(date: Time.now).first.price.to_i %><sub>/ night</sub></div>
   <p class="content">Стандартный трёхместный номер.</p>
   <div class="btn-book"><%= link_to "ПОСМОТРЕТЬ БОЛЬШЕ", standart_path %></div>
  </div>
 </div>

 <div class="col-md-6">
 <div class="room">
  <%= image_tag("rooms/img2.jpg", :alt => "room img", :class => "img-responsive", ) %>
  <div class="heading">Люкс</div>
   <div class="devider-rooms"></div>
   <div class="price">₴<%= @room_luxe.room_dates.where(date: Time.now).first.price.to_i %><sub>/ night</sub></div>
   <p class="content">Четырехместный люкс номер.</p>
   <div class="btn-book"><%= link_to "ПОСМОТРЕТЬ БОЛЬШЕ", luxe_path %></div>
 </div>
 </div>

 </div>
</div>
</section>
<!-- room end -->

app/views/rooms/luxe.html.erb
<!-- subheader -->
<section id="subheader">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>
          ЛЮКС
        </h1>
      </div>

      <!-- devider -->
      <div class="col-md-12">
        <div class="devider-page">
          <div class="devider-img-right">
          </div>
        </div>
      </div>

      <div class="col-md-12">
        <ul class="subdetail">
          <li>
            <a href="/">ДОМОЙ</a>
          </li>

          <li class="sep">/
          </li>

          <li>ЛЮКС
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- subheader end -->

<!-- services -->
<section class="room-detail whitepage">
  <div class="onStep" data-animation="fadeInUp" data-time="300">
    <div class="container">
      <div class="row">

        <!-- text detail -->
        <div class="col-md-4">
          <div class="detaillist">
            <h2>Люкс</h2>
            <div class="devider-rooms-detail"></div>
            <p>Люкс 4-местный.
            </p><br>
            <p>Люкс 4-местный.</p>

            <div class="space-single"></div>

            <h2>Услуги</h2>
            <div class="devider-rooms-detail"></div>
            <span><i class="ti-check-box"></i> Две двойные кровати</span>
            <span><i class="ti-check-box"></i> Диван</span>
            <span><i class="ti-check-box"></i> Душ</span>
            <span><i class="ti-check-box"></i> Бесплатный Wi-Fi</span>
            <span><i class="ti-check-box"></i> Телевизор</span>
            <span><i class="ti-check-box"></i> Кондиционер в номере</span>
            <div class="price"> ₴<%= @room.room_dates.where(date: Time.now).first.price.to_i %><sub>/ night</sub></div>
          </div>
        </div>
        <!-- text detail end -->

        <!-- detail img -->
        <div class="col-md-8">

          <div id="roomsBig" class="owl-carousel">
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
          </div>

          <div id="roomsSmall" class="owl-carousel">
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
          </div>
          <a class="btn-book-2 popup-form" href="#reservation">ЗАБРОНИРОВАТЬ</a>
        </div>
        <!-- detail img end -->

        <div class="space-single"></div>

      </div>
    </div>
  </div>
</section>
<!-- services end -->

<!-- Reservation start -->
<div class="white-popup-block mfp-hide animbounceInDown" data-time="0" id="reservation">
  <form action="#" id="form1" method="post" name="form1">
    <div class="row">

      <div class="col-sm-12 form-group">
        <select class="form-control" id="selectroom">
          <optgroup label="Выберите номер">
            <option value="Luxe">Люкс</option>
            <option value="Standart">Стандарт</option>
          </optgroup>
        </select>
      </div>

      <div class="col-md-12 form-group">
        <div class="input-group">
          <input type="text" name="date1" id="date1" class="form-control fox1" placeholder="ДАТА ВЪЕЗДА">
          <div class="input-group-btn">
            <span class="icon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>


      <div class="col-md-12 form-group">
        <div class="input-group">
          <input type="text" name="date2" id="date2" class="form-control fox2" placeholder="ДАТА ВЫЕЗДА">
          <div class="input-group-btn">
            <span class="icon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>

      <div class="col-sm-12 form-group">
        <input id="personbook" name="personbook" placeholder="ФАМИЛИЯ" type="text">
      </div>

      <div class="col-sm-12 form-group">
        <input id="namebook" name="namebook" placeholder="ИМЯ" type="text">
      </div>

      <div class="col-sm-12 form-group">
        <input id="emailbook" name="emailbook" placeholder="EMAIL" type="text">
      </div>

      <div class="col-sm-12 form-group">
        <input id="phonebook" name="phonebook" placeholder="ТЕЛЕФОН" type="text">
      </div>

      <div class="col-sm-12 form-group">
        <textarea cols="50" id="messagebook" name="message" placeholder="ВАШЕ СООБЩЕНИЕ(ОСОБЫЕ ПОЖЕЛАНИЯ)" rows="2"></textarea>
      </div>

      <div class="success-white" id="mail_success">Спасибо резервация выслана!</div>
      <div class="error-white" id="mail_failed">Что-то не так...</div>
      <button class="btn-content" id="send">ЗАБРОНИРОВАТЬ</button>

    </div>
  </form>
</div>
<!-- Reservation end -->

app/views/rooms/standart.html.erb
<!-- subheader -->
<section id="subheader">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>
          СТАНДАРТ
        </h1>
      </div>

      <!-- devider -->
      <div class="col-md-12">
        <div class="devider-page">
          <div class="devider-img-right">
          </div>
        </div>
      </div>

      <div class="col-md-12">
        <ul class="subdetail">
          <li>
            <a href="/">ДОМОЙ</a>
          </li>

          <li class="sep">/
          </li>

          <li>СТАНДАРТ
          </li>
        </ul>
      </div>
    </div>
  </div>
</section>
<!-- subheader end -->

<!-- services -->
<section class="room-detail whitepage">
  <div class="onStep" data-animation="fadeInUp" data-time="300">
    <div class="container">
      <div class="row">

        <!-- text detail -->
        <div class="col-md-4">
          <div class="detaillist">
            <h2>Стандарт</h2>
            <div class="devider-rooms-detail"></div>
            <p>Стандартный трёхместный номер.
            </p><br>
            <p>Стандартный трёхместный номер.</p>

            <div class="space-single"></div>

            <h2>Услуги</h2>
            <div class="devider-rooms-detail"></div>
            <span><i class="ti-check-box"></i> Двойная кровать</span>
            <span><i class="ti-check-box"></i> Диван</span>
            <span><i class="ti-check-box"></i> Душ</span>
            <span><i class="ti-check-box"></i> Бесплатный Wi-Fi</span>
            <span><i class="ti-check-box"></i> Телевизор</span>
            <span><i class="ti-check-box"></i> Кондиционер в номере</span>
            <div class="price">₴<%= @room.room_dates.where(date: Time.now).first.price.to_i %> <sub>/ night</sub></div>
          </div>
        </div>
        <!-- text detail end -->

        <!-- detail img -->
        <div class="col-md-8">

          <div id="roomsBig" class="owl-carousel">
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
          </div>

          <div id="roomsSmall" class="owl-carousel">
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
            <div class="item"><%= image_tag("rooms/img2.jpg", :alt => "img" ) %></div>
          </div>
          <a class="btn-book-2 popup-form" href="#reservation">ЗАБРОНИРОВАТЬ</a>
        </div>
        <!-- detail img end -->

        <div class="space-single"></div>

      </div>
    </div>
  </div>
</section>
<!-- services end -->

<!-- Reservation start -->
<div class="white-popup-block mfp-hide animbounceInDown" data-time="0" id="reservation">
  <form action="#" id="form1" method="post" name="form1">
    <div class="row">

      <div class="col-sm-12 form-group">
        <select class="form-control" id="selectroom">
          <optgroup label="Выберите номер">
            <option value="Standart">Стандарт</option>
            <option value="Luxe">Люкс</option>
          </optgroup>
        </select>
      </div>

      <div class="col-md-12 form-group">
        <div class="input-group">
          <input type="text" name="date1" id="date1" class="form-control fox1" placeholder="ДАТА ВЪЕЗДА">
          <div class="input-group-btn">
            <span class="icon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>


      <div class="col-md-12 form-group">
        <div class="input-group">
          <input type="text" name="date2" id="date2" class="form-control fox2" placeholder="ДАТА ВЫЕЗДА">
          <div class="input-group-btn">
            <span class="icon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>

      <div class="col-sm-12 form-group">
        <input id="personbook" name="personbook" placeholder="ФАМИЛИЯ" type="text">
      </div>

      <div class="col-sm-12 form-group">
        <input id="namebook" name="namebook" placeholder="ИМЯ" type="text">
      </div>

      <div class="col-sm-12 form-group">
        <input id="emailbook" name="emailbook" placeholder="EMAIL" type="text">
      </div>

      <div class="col-sm-12 form-group">
        <input id="phonebook" name="phonebook" placeholder="ТЕЛЕФОН" type="text">
      </div>

      <div class="col-sm-12 form-group">
        <textarea cols="50" id="messagebook" name="message" placeholder="ВАШЕ СООБЩЕНИЕ(ОСОБЫЕ ПОЖЕЛАНИЯ)" rows="2"></textarea>
      </div>

      <div class="success-white" id="mail_success">Спасибо резервация выслана!</div>
      <div class="error-white" id="mail_failed">Что-то не так...</div>
      <button class="btn-content" id="send">ЗАБРОНИРОВАТЬ</button>

    </div>
  </form>
</div>
<!-- Reservation end -->